
spring: 
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: '@project.artifactId@'

logging:
  file: 
    name: '@log.file.path@'
  level:
    root: '@custom.project.log.level@'
    
 
ggserver: 
  port: 1528
  websocketPath: /websocke